apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # Terminal: echo -n yaNoEssecretoSecretoso | base64
  # Base64 String yaNoEssecretoSecretoso === c2VjcmV0b1NlY3JldG9zbw==
  JWT_SEED: eWFOb0Vzc2VjcmV0b1NlY3JldG9zbw==
