apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # Terminal: echo -n superman@google.com | base64
  # Base64 String superman@google.com === c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==

  # Base64 String EstoPasoPaso === RXN0b1Bhc29QYXNv
  DB_PASSWORD: RXN0b1Bhc29QYXNv
